spring:
  application:
    name: customer-management
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fiap_customer_management
    username: postgres
    password: 123456

springdoc:
  swagger-ui:
    operationsSorter: method

server:
  port: 0
  forward-headers-strategy: framework
  # Uncomment to control stack trace inclusion on errors
  # error:
  #   include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
info:
  app:
    name: Fiap Customer Management
    version: 1.0.0
    description: Spring Boot Fiap Customer Management Service
